# Generated by Django 3.0.3 on 2020-02-10 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPiece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('king', 'king'), ('queen', 'queen'), ('rook', 'rook'), ('knight', 'knight'), ('bishop', 'bishop'), ('pawn', 'pawn')], max_length=20)),
                ('color', models.CharField(choices=[('white', 'white'), ('black', 'black')], max_length=20)),
            ],
        ),
    ]
