# Generated by Django 3.0.3 on 2020-02-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('king', 'king'), ('queen', 'queen'), ('rook', 'rook'), ('knight', 'knight'), ('bishop', 'bishop'), ('pawn', 'pawn')], max_length=20)),
                ('color', models.CharField(choices=[('white', 'white'), ('black', 'black')], max_length=20)),
            ],
        ),
    ]
